module.exports.countries = [
	['United States',23000 , 200, 30, 0, 'Major Superpowers', '🇺🇸'],
	['China', 17700, 120, 20, 0, 'Major Superpowers', '🇨🇳'],

	['Japan', 4900, 50, 10, 0, 'Major Powers', '🇯🇵'],
	['Germany', 4300, 20, 5, 0, 'Major Powers', '🇩🇪'],
	['India', 3200, 90, 10, 0, 'Major Powers', '🇮🇳'],
	['United Kingdom', 3100, 90, 10, 0, 'Major Powers', '🇬🇧'],
	['France', 2900, 60, 15, 0, 'Major Powers', '🇫🇷'],
	['Russia', 1700, 100, 25, 0, 'Major Powers', '🇷🇺'],

	['Italy', 2100, 40, 5, 0, 'Regional Powers', '🇮🇹'],
	['Canada', 1900, 10, 5, 0, 'Regional Powers', '🇨🇦'],
	['South Korea', 1800, 60, 15, 0, 'Regional Powers', '🇰🇷'],
	['Australia', 1700, 10, 3, 0, 'Regional Powers', '🇦🇺'],
	['Brazil', 1600, 20, 5, 0, 'Regional Powers', '🇧🇷'],
	['Spain', 1400, 20, 5, 0, 'Regional Powers', '🇪🇸'],
	['Mexico', 1300, 30, 5, 0, 'Regional Powers', '🇲🇽'],
	['Indonesia', 1100, 20, 5, 0, 'Regional Powers', '🇮🇩'],
	['The Netherlands', 1000, 10, 3, 0, 'Regional Powers', '🇳🇱'],
	['Saudi Arabia', 900, 30, 5, 0, 'Regional Powers', '🇸🇦'],
	['Turkey', 800, 30, 5, 0, 'Regional Powers', '🇹🇷'],
	['Switzerland', 800, 20, 5, 0, 'Regional Powers', '🇨🇭'],
	['Taiwan', 800, 20, 5, 0, 'Regional Powers', '🇹🇼'],
	['Poland', 700, 20, 5, 0, 'Regional Powers', '🇵🇱'],
	['Sweden', 600, 10, 3, 0, 'Regional Powers', '🇸🇪'],
	['Iran', 600, 40, 15, 0, 'Regional Powers', '🇮🇷'],
	['Belgium', 600, 10, 3, 0, 'Regional Powers', '🇧🇪'],
	['Thailand', 500, 10, 3, 0, 'Regional Powers', '🇹🇭'],
	['Argentina', 500, 10, 3, 0, 'Regional Powers', '🇦🇷'],
	['Israel', 500, 50, 15, 0, 'Regional Powers', '🇮🇱'],
	['North Korea', 20, 50, 0, 0, 'Regional Powers', '🇰🇵'],

	['Ireland', 500, 5, 3, 0, 'Minor Powers', '🇮🇪'],
	['Norway', 500, 5, 3, 0, 'Minor Powers', '🇳🇴'],
	['Austria', 500, 3, 0, 0, 'Minor Powers', '🇦🇹'],
	['Nigeria', 400, 20, 0, 0, 'Minor Powers', '🇳🇬'],
	['Egypt', 400, 20, 0, 0, 'Minor Powers', '🇪🇬'],
	['South Africa', 400, 15, 3, 0, 'Minor Powers', '🇿🇦'],
	['Bangladesh', 400, 10, 0, 0, 'Minor Powers', '🇧🇩'],
	['United Arab Emirates', 400, 10, 0, 0, 'Minor Powers', '🇦🇪'],
	['Denmark', 400, 5, 0, 0, 'Minor Powers', '🇩🇰'],
	['Singapore', 400, 2, 0, 0, 'Minor Powers', '🇸🇬'],
	['Philippines', 400, 25, 0, 0, 'Minor Powers', '🇵🇭'],
	['Malaysia', 400, 15, 0, 0, 'Minor Powers', '🇲🇾'],
	['Vietnam', 350, 10, 0, 0, 'Minor Powers', '🇻🇳'],
	['Pakistan', 350, 40, 5, 0, 'Minor Powers', '🇵🇰'],
	['Chile', 300, 10, 0, 0, 'Minor Powers', '🇨🇱'],
	['Colombia', 300, 15, 0, 0, 'Minor Powers', '🇨🇴'],
	['Finland', 300, 5, 0, 0, 'Minor Powers', '🇫🇮'],
	['Romania', 300, 5, 0, 0, 'Minor Powers', '🇷🇴'],
	['Czech Republic', 300, 5, 0, 0, 'Minor Powers', '🇨🇿'],
	['Portugal', 250, 5, 0, 0, 'Minor Powers', '🇵🇹'],
	['New Zealand', 250, 5, 0, 0, 'Minor Powers', '🇳🇿'],
	['Peru', 250, 10, 0, 0, 'Minor Powers', '🇵🇪'],
	['Greece', 200, 10, 0, 0, 'Minor Powers', '🇬🇷'],
	['Iraq', 200, 10, 0, 0, 'Minor Powers', '🇮🇶'],
	['Ukraine', 200, 10, 0, 0, 'Minor Powers', '🇺🇦'],
	['Kazakhstan', 200, 5, 0, 0, 'Minor Powers', '🇰🇿'],
	['Hungary', 200, 5, 0, 0, 'Minor Powers', '🇭🇺'],
	['Algeria', 150, 10, 0, 0, 'Minor Powers', '🇩🇿'],
	['Morocco', 150, 10, 0, 0, 'Minor Powers', '🇲🇦'],
	['Cuba', 100, 20, 0, 0, 'Minor Powers', '🇨🇺'],
	['Slovakia', 100, 3, 0, 0, 'Minor Powers', '🇸🇰'],
	['Venezuela', 100, 20, 0, 0, 'Minor Powers', '🇻🇪'],
	['Kenya', 100, 3, 0, 0, 'Minor Powers', '🇰🇪'],
	['Ethiopia', 100, 20, 0, 0, 'Minor Powers', '🇪🇹'],

	['Qatar', 200, 5, 0, 0, 'Insignificant Powers', '🇶🇦'],
	['Kuwait', 150, 5, 0, 0, 'Insignificant Powers', '🇰🇼'],
	['Ecuador', 100, 3, 0, 0, 'Insignificant Powers', '🇪🇨'],
	['Dominican Republic', 100, 3, 0, 0, 'Insignificant Powers', '🇩🇴'],
	['Oman', 100, 3, 0, 0, 'Insignificant Powers', '🇴🇲'],
	['Guatemala', 100, 3, 0, 0, 'Insignificant Powers', '🇬🇹'],
	['Sri Lanka', 100, 3, 0, 0, 'Insignificant Powers', '🇱🇰'],
	['Bulgaria', 100, 3, 0, 0, 'Insignificant Powers', '🇧🇬'],
	['Ghana', 80, 3, 0, 0, 'Insignificant Powers', '🇬🇭'],
	['Angola', 70, 3, 0, 0, 'Insignificant Powers', '🇦🇴'],
	['Tanzania', 70, 3, 0, 0, 'Insignificant Powers', '🇹🇿'],
	['Ivory Coast', 70, 3, 0, 0, 'Insignificant Powers', '🇨🇮'],
	['Uzbekistan', 70, 3, 0, 0, 'Insignificant Powers', '🇺🇿'],
	['Croatia', 70, 3, 0, 0, 'Insignificant Powers', '🇭🇷'],
	['Belarus', 70, 15, 0, 0, 'Insignificant Powers', '🇧🇾'],
	['Lithuania', 70, 3, 0, 0, 'Insignificant Powers', '🇱🇹'],
	['Costa Rica', 70, 0, 0, 0, 'Insignificant Powers', '🇨🇷'],
	['Panama', 60, 0, 0, 0, 'Insignificant Powers', '🇵🇦'],
	['Serbia', 60, 3, 0, 0, 'Insignificant Powers', '🇷🇸'],
	['Slovenia', 60, 3, 0, 0, 'Insignificant Powers', '🇸🇮'],
	['Uruguay', 60, 3, 0, 0, 'Insignificant Powers', '🇺🇾'],
	['Myanmar', 60, 3, 0, 0, 'Insignificant Powers', '🇲🇲'],
	['Azerbaijan', 60, 10, 0, 0, 'Insignificant Powers', '🇦🇿'],
	['Turkmenistan', 50, 3, 0, 0, 'Insignificant Powers', '🇹🇲'],
	['DR Congo', 50, 3, 0, 0, 'Insignificant Powers', '🇨🇩'],
	['Tunisia', 50, 3, 0, 0, 'Insignificant Powers', '🇹🇳'],
	['Cameroon', 50, 3, 0, 0, 'Insignificant Powers', '🇨🇲'],
	['Jordan', 50, 3, 0, 0, 'Insignificant Powers', '🇯🇴'],
	['Uganda', 40, 3, 0, 0, 'Insignificant Powers', '🇺🇬'],
	['Paraguay', 40, 3, 0, 0, 'Insignificant Powers', '🇵🇾'],
	['Bolivia', 40, 3, 0, 0, 'Insignificant Powers', '🇧🇴'],
	['Latvia', 40, 1, 0, 0, 'Insignificant Powers', '🇱🇻'],
	['Libya', 40, 3, 0, 0, 'Insignificant Powers', '🇱🇾'],
	['Bahrain', 40, 1, 0, 0, 'Insignificant Powers', '🇧🇭'],
	['Lebanon', 40, 10, 0, 0, 'Insignificant Powers', '🇱🇧'],
	['Estonia', 40, 1, 0, 0, 'Insignificant Powers', '🇪🇪'],
	['Nepal', 40, 3, 0, 0, 'Insignificant Powers', '🇳🇵'],
	['Sudan', 40, 10, 0, 0, 'Insignificant Powers', '🇸🇩'],

	['El Salvador', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇸🇻'],
	['Honduras', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇭🇳'],
	['Cyprus', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇨🇾'],
	['Senegal', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇸🇳'],
	['Cambodia', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇰🇭'],
	['Papua New Guinea', 30, 4, 0, 0, 'Minor Insignificant Powers', '🇵🇬'],
	['Iceland', 30, 2, 0, 0, 'Minor Insignificant Powers', '🇮🇸'],
	['Zimbabwe', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇿🇼'],
	['Bosnia and Herzegovina', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇧🇦'],
	['Zambia', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇿🇲'],
	['Burkina Faso', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇧🇫'],
	['Syria', 20, 20, 0, 0, 'Minor Insignificant Powers', '🇸🇾'],
	['Mali', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇱'],
	['Laos', 20, 5, 0, 0, 'Minor Insignificant Powers', '🇱🇦'],
	['Haiti', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇭🇹'],
	['Georgia', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇬🇪'],
	['Gabon', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇬🇦'],
	['Albania', 20, 1, 0, 0, 'Minor Insignificant Powers', '🇦🇱'],
	['Palestine', 20, 5, 0, 0, 'Minor Insignificant Powers', '🇵🇸'],
	['Malta', 20, 0, 0, 0, 'Minor Insignificant Powers', '🇲🇹'],
	['Benin', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇧🇯'],
	['Botswana', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇧🇼'],
	['Chad', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇹🇩'],
	['Guinea', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇬🇳'],
	['Mozambique', 20, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇿'],
	['Mongolia', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇳'],
	['Afghanistan', 15, 20, 0, 0, 'Minor Insignificant Powers', '🇦🇫'],
	['Niger', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇳🇪'],
	['Jamaica', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇯🇲'],
	['Madagascar', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇬'],
	['Nicaragua', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇳🇮'],
	['Brunei', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇧🇳'],
	['North Macedonia', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇰'],
	['Armenia', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇦🇲'],
	['Moldova', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇲🇩'],
	['Congo', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇨🇬'],
	['Equatorial Guinea', 15, 2, 0, 0, 'Minor Insignificant Powers', '🇬🇶'],
	['Namibia', 15, 1, 0, 0, 'Minor Insignificant Powers', '🇳🇦'],
	['Malawi', 15, 1, 0, 0, 'Minor Insignificant Powers', '🇲🇼'],
	['Mauritius', 15, 1, 0, 0, 'Minor Insignificant Powers', '🇲🇺'],
	['Bahamas', 10, 0, 0, 0, 'Minor Insignificant Powers', '🇧🇸'],
	['Rwanda', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇷🇼'],
	['Mauritania', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇲🇷'],
	['Yemen', 10, 10, 0, 0, 'Minor Insignificant Powers', '🇾🇪'],
	['Kosovo', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇽🇰'],
	['Tajikistan', 10, 3, 0, 0, 'Minor Insignificant Powers', '🇹🇯'],
	['Kyrgyzstan', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇰🇬'],
	['Togo', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇹🇬'],
	['Guyana', 10, 1, 0, 0, 'Minor Insignificant Powers', '🇬🇾'],
	['Somalia', 10, 5, 0, 0, 'Minor Insignificant Powers', '🇸🇴'],
	['Montenegro', 5, 1, 0, 0, 'Minor Insignificant Powers', '🇲🇪'],
	['Eswatini', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇸🇿'],
	['South Sudan', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇸🇸'],
	['Fiji', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇫🇯'],
	['Sierra Leone', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇸🇱'],
	['Burundi', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇧🇮'],
	['Djibouti', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇩🇯'],
	['Greenland', 5, 0, 0, 0, 'Minor Insignificant Powers', '🇬🇱'],
	['Suriname', 3, 0, 0, 0, 'Minor Insignificant Powers', '🇸🇷'],

	['Central African Republic', 3, 0, 0, 0, 'Very Minor Insignificant Powers', '🇨🇫'],
	['Belize', 3, 0, 0, 0, 'Very Minor Insignificant Powers', '🇧🇿'],
	['Liberia', 3, 0, 0, 0, 'Very Minor Insignificant Powers', '🇱🇷'],
	['Bhutan', 3, 0, 0, 0, 'Very Minor Insignificant Powers', '🇧🇹'],
	['Lesotho', 3, 0, 0, 0, 'Very Minor Insignificant Powers', '🇱🇸'],
	['Eritrea', 3, 2, 0, 0, 'Very Minor Insignificant Powers', '🇪🇷'],
	['Gambia', 2, 0, 0, 0, 'Very Minor Insignificant Powers', '🇬🇲'],
	['Cape Verde', 2, 0, 0, 0, 'Very Minor Insignificant Powers', '🇨🇻'],
	['Saint Lucia', 2, 0, 0, 0, 'Very Minor Insignificant Powers', '🇱🇨'],
	['Guinea-Bissau', 2, 0, 0, 0, 'Very Minor Insignificant Powers', '🇬🇼'],
	['Vanuatu', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇻🇺'],
	['Dominica', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇩🇲'],
	['Tonga', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇹🇴'],
	['Micronesia', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇫🇲'],
	['Marshall Islands', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇲🇭'],
	['Kiribati', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇰🇮'],
	['Palau', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇵🇼'],
	['Tuvalu', 1, 0, 0, 0, 'Very Minor Insignificant Powers', '🇹🇻'],
	
	['Hong Kong', 400, 1, 0, 0, 'Microstates', '🇭🇰'],
	['Vatican City', 200, 0, 0, 0, 'Microstates', '🇻🇦'],
	['Macau', 300, 0, 0, 0, 'Microstates', '🇱🇺'],
	['Luxembourg', 100, 2, 0, 0, 'Microstates', '🇱🇺'],
	['Trinidad and Tobago', 30, 0, 0, 0, 'Microstates', '🇹🇹'],
	['Monaco', 10, 0, 0, 0, 'Microstates', '🇲🇨'],
	['Maldives', 5, 0, 0, 0, 'Microstates', '🇲🇻'],
	['Barbados', 5, 0, 0, 0, 'Microstates', '🇧🇧'],
	['Andorra', 5, 0, 0, 0, 'Microstates', '🇦🇩'],
	['Aruba', 3, 0, 0, 0, 'Microstates', '🇦🇼'],
	['East Timor', 2, 0, 0, 0, 'Microstates', '🇹🇱'],
	['San Marino', 2, 0, 0, 0, 'Microstates', '🇸🇲'],
	['Solomon Islands', 2, 0, 0, 0, 'Microstates', '🇸🇧'],
	['Antigua and Barbuda', 2, 0, 0, 0, 'Microstates', '🇦🇬'],
	['Comoros', 1, 0, 0, 0, 'Microstates', '🇰🇲'],
	['Seychelles', 1, 0, 0, 0, 'Microstates', '🇸🇨'],
	['Grenada', 1, 0, 0, 0, 'Microstates', '🇬🇩'],
	['Saint Vincent and the Grenadines	', 1, 0, 0, 0, 'Microstates', '🇻🇨'],
	['Saint Kitts and Nevis	', 1, 0, 0, 0, 'Microstates', '🇰🇳'],
	['Samoa	', 1, 0, 0, 0, 'Microstates', '🇼🇸'],
	['São Tomé and Príncipe	', 1, 0, 0, 0, 'Microstates', '🇸🇹'],
	['Nauru', 1, 0, 0, 0, 'Microstates', '🇳🇷'],
];
